services:
  postgres:
    image: postgres:16
    container_name: rozel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rozel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rozel-postgres:/var/lib/postgresql/data

volumes:
  rozel-postgres:
